# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TODOappFinantech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TODOappFinantech
  pod 'Then'
  pod 'SnapKit'
end
